# Generated by Django 5.2.11 on 2026-03-01 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('alojamiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservas.alojamiento')),
                ('numero_piso', models.IntegerField()),
                ('tiene_ascensor', models.BooleanField()),
                ('tiene_porteria', models.BooleanField()),
            ],
            bases=('reservas.alojamiento',),
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('alojamiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservas.alojamiento')),
                ('numero_pisos', models.IntegerField()),
                ('tiene_patio', models.BooleanField()),
                ('tiene_garaje', models.BooleanField()),
            ],
            bases=('reservas.alojamiento',),
        ),
    ]
