# Generated by Django 5.2.11 on 2026-03-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_apartamento_casa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='alojamiento_ptr',
        ),
        migrations.DeleteModel(
            name='Apartamento',
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
    ]
