# Generated by Django 5.2.8 on 2026-05-21 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_apartamento_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='descripcion_completa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='arrendador',
            name='documento_identidad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cancelada_por',
            field=models.CharField(blank=True, choices=[('estudiante', 'Estudiante'), ('arrendador', 'Arrendador')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='renovacion_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='reservas.reserva'),
        ),
        migrations.CreateModel(
            name='AlojamientoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='alojamientos/%Y/%m/')),
                ('orden', models.IntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reservas.alojamiento')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
